horizon: 24
history: 104

data:
  root_path: ./datasets
  data_path: ILI.csv

model:
  model_type: PatchTST_NN
  model_params:
    e_layers: 3
    n_heads: 4
    d_model: 16
    d_ff: 128
    dropout: 0.3
    fc_dropout: 0.3
    head_dropout: 0
    patch_len: 24
    stride: 2
    channel_independent: True

scheduler: 
  scheduler_type: LambdaLR
  scheduler_params:
    lr_lambda: "lambda epoch: 1.0"

trainer_params:
  n_epochs: 100
  batch_size: 16
  optimizer_params:
    lr: 0.0025
  num_workers: 15
  early_stopping_patience: 100
  best_by_metric: True
  save_to_dir: False
  drop_last: True
  device: cuda:0
