horizon: 96
history: 336

data:
  root_path: ./datasets
  data_path: ETTh1.csv

multivariate: True

model:
  model_type: CycleNet_NN
  model_params:
    cycle_len: 24
    model_type: linear
    channel_independent: True

scheduler: 
  scheduler_type: LambdaLR
  scheduler_params:
    lr_lambda: "lambda epoch: 1.0"

trainer_params:
  n_epochs: 30
  batch_size: 256
  optimizer_params:
    lr: 0.01
  num_workers: 15
  early_stopping_patience: 5
  best_by_metric: True
  save_to_dir: False
  drop_last: True
  device: cuda:0

seed: [2025, 2026, 2027]
