horizon: 96
history: 336

data:
  root_path: ./datasets
  data_path: ETTh1.csv

model:
  model_type: PatchTST_NN
  model_params:
    e_layers: 3
    n_heads: 4
    d_model: 16
    d_ff: 128
    dropout: 0.3
    fc_dropout: 0.3
    head_dropout: 0
    patch_len: 16
    stride: 8
    channel_independent: True

scheduler: 
  scheduler_type: LambdaLR
  scheduler_params:
    lr_lambda: "lambda epoch: 1.0 if epoch < 10 else 0.1"

trainer_params:
  n_epochs: 100
  batch_size: 128
  optimizer_params:
    lr: 0.0001
  num_workers: 15
  early_stopping_patience: 100
  best_by_metric: True
  save_to_dir: False
  drop_last: True
  device: cuda:0
